testing automation flow

diff --git a/.github/workflows/CAdeploy.yml b/.github/workflows/CAdeploy.yml
--- a/.github/workflows/CAdeploy.yml
+++ b/.github/workflows/CAdeploy.yml
@@ -5,18 +5,7 @@ on:
     branches:
       - main
     paths:
-      - 'ClientAdvisor/**'
-  workflow_dispatch:
-    inputs:
-      powerbiURL:
-        description: 'Enter the powerbi url'
-        required: true
-        default: "test.com"
-      applicationName:
-        description: 'Enter the application name'
-        required: true
-        default: "test"
-      
+      - 'ClientAdvisor/**'   
 
 jobs:
   deploy:
@@ -40,7 +29,6 @@ jobs:
 
       - name: Generate Resource Group Name
         id: generate_rg_name
-        if: ${{ github.event_name != 'workflow_dispatch'}}
         run: |
           echo "Generating a unique resource group name..."
           TIMESTAMP=$(date +%Y%m%d%H%M%S)
@@ -53,7 +41,7 @@ jobs:
       - name: Check and Create Resource Group
         id: check_create_rg
         run: |
-          echo "GRESOURCE_GROUP: ${{ env.RESOURCE_GROUP_NAME }}"
+          echo "RESOURCE_GROUP: ${{ env.RESOURCE_GROUP_NAME }}"
           set -e  
           echo "Checking if resource group exists..."
           rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
@@ -66,7 +54,6 @@ jobs:
       
       - name: Generate Unique Solution Prefix
         id: generate_solution_prefix
-        if: ${{ github.event_name != 'workflow_dispatch'}}
         run: |
           set -e
           COMMON_PART="pslc"
@@ -76,25 +63,26 @@ jobs:
           echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
           echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}"
           
-      - name: Deploy Bicep Template
-        id: deploy
-        if: ${{ github.event_name != 'workflow_dispatch'}}
-        run: |
-          set -e
-          az deployment group create \
-            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
-            --template-file ClientAdvisor/Deployment/bicep/main.bicep \
-            --parameters solutionPrefix=${{ env.SOLUTION_PREFIX }} cosmosLocation=eastus2
+      # - name: Deploy Bicep Template
+      #   id: deploy
+      #   run: |
+      #     set -e
+      #     az deployment group create \
+      #       --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
+      #       --template-file ClientAdvisor/Deployment/bicep/main.bicep \
+      #       --parameters solutionPrefix=${{ env.SOLUTION_PREFIX }} cosmosLocation=eastus2
 
       - name: Update PowerBI URL
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.powerbiURL != 'TBD' }}
+        if: success()
         run: |
           set -e
-          echo "application name: ${{ github.event.inputs.applicationName }}"
-          echo "powerBI URL: ${{ github.event.inputs.powerbiURL }}"
-          az webapp config appsettings set --name ${{ github.event.inputs.applicationName }} --resource-group pslautomationbyoa5 --settings VITE_POWERBI_EMBED_URL=${{ github.event.inputs.powerbiURL }}
+          COMMON_PART="-app-service"
+          application_name="$${{ env.SOLUTION_PREFIX }}{COMMON_PART}"
+          echo "application name: application_name"
+          echo "powerBI URL: ${{ vars.VITE_POWERBI_EMBED_URL }}"
+          az webapp config appsettings set --name application_name --resource-group pslautomationbyoa5 --settings VITE_POWERBI_EMBED_URL=${{ vars.VITE_POWERBI_EMBED_URL }}
           # Restart App Service
-          az webapp restart --resource-group $resourceGroup --name $appServiceName
+          az webapp restart --resource-group pslautomationbyoa5 --name application_name
           # Check if the update was successful
           if [ $? -eq 0 ]; then
               echo "Power BI URL updated successfully."
@@ -102,38 +90,38 @@ jobs:
               echo "Failed to update Power BI URL."
           fi
 
-      - name: Delete Bicep Deployment
-        if: ${{ success() &&  github.event_name != 'workflow_dispatch' }}
-        run: |
-          set -e  
-          echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
-          if [ "$rg_exists" = "true" ]; then
-            echo "Resource group exist. Cleaning..."
-            az group delete \
-                --name ${{ env.RESOURCE_GROUP_NAME }} \
-                --yes \
-                --no-wait
-            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
-          else
-            echo "Resource group does not exists."
-          fi
+      # - name: Delete Bicep Deployment
+      #   if: success()
+      #   run: |
+      #     set -e  
+      #     echo "Checking if resource group exists..."
+      #     rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+      #     if [ "$rg_exists" = "true" ]; then
+      #       echo "Resource group exist. Cleaning..."
+      #       az group delete \
+      #           --name ${{ env.RESOURCE_GROUP_NAME }} \
+      #           --yes \
+      #           --no-wait
+      #       echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
+      #     else
+      #       echo "Resource group does not exists."
+      #     fi
       
-      - name: Send Notification on Failure
-        if: failure()
-        run: |
-          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+      # - name: Send Notification on Failure
+      #   if: failure()
+      #   run: |
+      #     RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
       
-          # Construct the email body
-          EMAIL_BODY=$(cat <<EOF
-          {
-            "body": "<p>Dear Team,</p><p>We would like to inform you that the Client Advisor Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
-          }
-          EOF
-          )
+      #     # Construct the email body
+      #     EMAIL_BODY=$(cat <<EOF
+      #     {
+      #       "body": "<p>Dear Team,</p><p>We would like to inform you that the Client Advisor Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
+      #     }
+      #     EOF
+      #     )
       
-          # Send the notification
-          curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
-            -H "Content-Type: application/json" \
-            -d "$EMAIL_BODY" || echo "Failed to send notification"
+      #     # Send the notification
+      #     curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
+      #       -H "Content-Type: application/json" \
+      #       -d "$EMAIL_BODY" || echo "Failed to send notification"
 
