added tags in CAdeploy.yml file

diff --git a/.github/workflows/CAdeploy.yml b/.github/workflows/CAdeploy.yml
--- a/.github/workflows/CAdeploy.yml
+++ b/.github/workflows/CAdeploy.yml
@@ -105,7 +105,17 @@ jobs:
           rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
           if [ "$rg_exists" = "false" ]; then
             echo "Resource group does not exist. Creating..."
-            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.AZURE_LOCATION }} || { echo "Error creating resource group"; exit 1; }
+
+            # Generate current timestamp in desired format: YYYY-MM-DDTHH:MM:SS.SSSSSSSZ
+            current_date=$(date -u +"%Y-%m-%dT%H:%M:%S.%7NZ")
+            az group create --name ${{ env.RESOURCE_GROUP_NAME }} \
+                            --location ${{ env.AZURE_LOCATION }} \
+                            --tags "CreatedBy=Deployment Lifecycle Automation Pipeline" \
+                                   "Purpose=Deploying and Cleaning Up Resources for Validation" \
+                                   "CreatedDate=$current_date" \
+                                   "ApplicationName=BYOC-Client Advisor Accelerator" \
+                                   "SecurityControl=Ignore" \
+            || { echo "Error creating resource group"; exit 1; }
           else
             echo "Resource group already exists."
           fi
