testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -26,27 +26,68 @@ jobs:
 
       - name: Install Bicep CLI
         run: az bicep install
+
+      - name: Generate Resource Group Name
+        id: generate_rg_name
+        run: |
+          echo "Generating a unique resource group name..."
+          TIMESTAMP=$(date +%Y%m%d%H%M%S)
+          COMMON_PART="pslautomationRes"
+          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
+          echo "##########################"
+          echo "$RESOURCE_GROUP_NAME"
+          echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$"
+          echo "${{ env.RESOURCE_GROUP_NAME }}"
+          echo "888888888888888888888888888"
+          echo "Generated SOLUTION_PREFIX: ${RESOURCE_GROUP_NAME}" 
       
       - name: Check and Create Resource Group
         id: check_create_rg
         run: |
           set -e  
           echo "Checking if resource group exists..."
-          rg_exists=$(az group exists --name pslautomationbyoa2)
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
           if [ "$rg_exists" = "false" ]; then
             echo "Resource group does not exist. Creating..."
-            az group create --name pslautomationbyoa2 --location eastus || { echo "Error creating resource group"; exit 1; }
+            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location eastus || { echo "Error creating resource group"; exit 1; }
           else
             echo "Resource group already exists."
           fi
 
+      - name: Generate Unique Solution Prefix
+        id: generate_solution_prefix
+        run: |
+          set -e
+          COMMON_PART="psl"
+          TIMESTAMP=$(date +%s)  
+          UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 2) 
+          UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
+          echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
+          echo "ssssssssssssssssssssssssssssssssssssssssssssssssssss"
+          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
+
       - name: Deploy Bicep Template
         id: deploy
         run: |
+          set -e
           az deployment group create \
-            --resource-group pslautomationbyoa2 \
+            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
             --template-file ResearchAssistant/Deployment/bicep/main.bicep \
-            --parameters  \
+            --parameters solutionPrefix=pslre2 
+
+      - name: Delete Bicep Deployment
+        run: |
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "true" ]; then
+            echo "Resource group exist. Cleaning..."
+            az group delete \
+                --name ${{ env.RESOURCE_GROUP_NAME }} \
+                --yes \
+                --no-wait
+          
          
       - name: Send Notification on Failure
         if: failure()
