testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -39,12 +39,12 @@ jobs:
           fi
 
           
-      # - name: Assign Role to Service Principal
-      #   id: assign_role
-      #   run: |
-      #     set -e
-      #     echo "Assigning User Access Administrator role to the service principal..."
-      #     az role assignment create --assignee ${{ secrets.AZURE_CLIENT_ID }} --role "User Access Administrator" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/pslautomationbyoa2 || { echo "Error assigning role"; exit 1; }
+      - name: Assign Role to Service Principal
+        id: assign_role
+        run: |
+          set -e
+          echo "Assigning User Access Administrator role to the service principal..."
+          az role assignment create --assignee ${{ secrets.AZURE_CLIENT_ID }} --role "Owner" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/pslautomationbyoa2 || { echo "Error assigning role"; exit 1; }
           
       - name: Deploy Bicep Template
         id: deploy
