testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -53,21 +53,22 @@ jobs:
         id: deploy
         run: |
           set -e
-          output=$(az deployment group create \
+          output_file=$(mktemp)
+          az deployment group create \
             --resource-group pslautomationbyoa2 \
             --template-file ResearchAssistant/Deployment/bicep/main.bicep \
-            --parameters 2>&1) || {
-              echo "Deployment failed. Here is the error mesage:"
-              echo "###########################################################################"              
-              echo "$output" >> $GITHUB_ENV
-              echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"              
-              echo "$output"
-              echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"              
-              exit 1
+            --parameters solutionPrefix=pslre2 \
+            &> "$output_file" || {
+              echo "Command failed, capturing output and error."
             }
+          
+          output=$(< "$output_file")
+          echo "===============================================================================" 
+          echo "$output"
           echo "******************************************************************************" 
           echo "output=$output" >> $GITHUB_ENV
           echo "******************************************************************************" 
+          rm "$output_file"
       
       - name: Send Notification on Failure
         if: failure()
