testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -57,19 +57,30 @@ jobs:
           az deployment group create \
             --resource-group pslautomationbyoa2 \
             --template-file ResearchAssistant/Deployment/bicep/main.bicep \
-            --parameters solutionPrefix=pslre2 \
-            &> "$output_file" || {
-              echo "Command failed, capturing output and error."
-            }
+            --parameters \
+            &> "$output_file" || echo "Command failed, capturing output and error."
           
-          output=$(< "$output_file")
           echo "===============================================================================" 
-          echo "$output"
-          echo "******************************************************************************" 
-          echo "output=$output" >> $GITHUB_ENV
+          cat "$output_file"
+          echo "******************************************************************************"
+
+          # Extract only the lines containing 'error' or 'failed'
+          error_output=$(grep -i -e "error" -e "failed" "$output_file" || true)
+
+          echo "===============================================================================" 
+          cat "$error_output"
+          echo "******************************************************************************"
+
+
+          if [[ -n "$error_output" ]]; then
+            echo "error_output=$error_output" >> $GITHUB_ENV
+          else
+            echo "No errors found in the output."
+          fi
+
           echo "******************************************************************************" 
           rm "$output_file"
-      
+            
       - name: Send Notification on Failure
         if: failure()
         run: |
