testing automation flow

diff --git a/.github/workflows/RAdeploy.yml b/.github/workflows/RAdeploy.yml
--- a/.github/workflows/RAdeploy.yml
+++ b/.github/workflows/RAdeploy.yml
@@ -39,18 +39,22 @@ jobs:
           fi
 
           
-      - name: Assign Role to Service Principal
-        id: assign_role
-        run: |
-          set -e
-          echo "Assigning User Access Administrator role to the service principal..."
-          az role assignment create --assignee ${{ secrets.AZURE_CLIENT_ID }} --role "Owner" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/pslautomationbyoa2 || { echo "Error assigning role"; exit 1; }
+      # - name: Assign Role to Service Principal
+      #   id: assign_role
+      #   run: |
+      #     set -e
+      #     echo "Assigning Owner role to the service principal..."
+      #     az role assignment create --assignee ${{ secrets.AZURE_CLIENT_ID }} --role "Owner" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }} || { echo "Error assigning role"; exit 1; }
           
       - name: Deploy Bicep Template
         id: deploy
         run: |
           set -e
-          az deployment group create \
+          output=$(az deployment group create \
             --resource-group pslautomationbyoa2 \
             --template-file ResearchAssistant/Deployment/bicep/main.bicep \
-            --parameters solutionPrefix=pslre2
+            --parameters solutionPrefix=pslre2 --debug 2>&1) || {
+              echo "Deployment failed. Here is the error message:"
+              echo "$output"
+              exit 1
+            }
